environment:
    matrix:
        ## linux
        #- APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        #  APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
        #  compiler: gcc

        ## osx
        #- APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
        #  APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"
        #  compiler: clang

        # windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x64-vs2015"
          arch: amd64
          platform: x86
          compiler: msvc

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x64-vs2015"
          arch: x86
          platform: x64
          compiler: msvc


stack: python 3.7

init:
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    #- set "PYTHON_ROOT=C:\python37-x64"
    #- set "PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%"
    - cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install:
    - python -m pip install cython pkgconfig
    - 'if "%compiler%"=="msvc" vcpkg install ffnvcodec:%platform%-windows'
    - ls C:\Tools\vcpkg\packages\protobuf_x86-windows\lib\pkgconfig
    - ls C:\Tools\vcpkg\packages\protobuf_x86-windows\bin
    - 'if "%compiler%"=="msvc" set PKG_CONFIG_PATH=%PKG_CONFIG_PATH%;C:\Tools\vcpkg\packages\protobuf_x86-windows\lib\pkgconfig'
    - if "%compiler%"=="msvc"
        vcpkg install glib:%platform%-windows
                      libogg:%platform%-windows
                      libtheora:%platform%-windows
                      ffmpeg:%platform%-windows

build_script:
    - mkdir wheelhouse

    - 'if "%compiler%"=="msvc" python setup.py build_ext --inplace --force'
    - 'if "%compiler%"=="msvc" python setup.py sdist --dist-dir wheelhouse'
    - 'if "%compiler%"=="msvc" python setup.py bdist_wheel --dist-dir wheelhouse'

# after_build


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
