environment:
    matrix:
        ## linux
        #- APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        #  APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
        #  compiler: gcc

        ## osx
        #- APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
        #  APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"
        #  compiler: clang

        # windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x64-vs2015"

init:
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%

install:
    - 

build_script:
    - mkdir wheelhouse

    - ps: python -m pip install --upgrade pip
    - ps: python -m pip install scikit-build cython conan pytest
    - ps: python setup.py build_ext --inplace --force -- -D_CONAN=YES
    - ps: python setup.py test
    #- ps: python setup.py sdist --dist-dir wheelhouse
    #- ps: python setup.py bdist_wheel --dist-dir wheelhouse


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
