cache: c:\tools\vcpkg\installed\
environment:
  matrix:
    - PYTHON: "C:/Python27-x64"
      TRIPLET: x64-windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCPKG_BUILD: 1
      VCPKG_TOOLCHAIN: C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    - PYTHON: "C:/Python27"
      TRIPLET: x86-windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCPKG_BUILD: 1
      VCPKG_TOOLCHAIN: C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake

init:
  - cmd: set VCPKG_DEFAULT_TRIPLET=%TRIPLET%
#  - cmd: cd c:\tools\vcpkg                  # vcpkg 2020.02.04-nohash / VS 2019
#  - cmd: vcpkg update
  - cmd: git clone -b 2020.07 --single-branch https://github.com/Microsoft/vcpkg.git
  - cmd: cd vcpkg
  - cmd: .\bootstrap-vcpkg.bat
  - cmd: vcpkg install glib:%TRIPLET%       # 2.52.3-14-3
  - cmd: vcpkg install libogg:%TRIPLET%     # 1.3.4
  - cmd: vcpkg install libtheora:%TRIPLET%  # 1.2.0alpha1-20170719~vcpkg1-3
  - cmd: vcpkg install ffmpeg:%TRIPLET%     # 4.3.1
  - cmd: vcpkg install msinttypes:%TRIPLET% # 2018-02-25
  - cmd: vcpkg integrate install
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -U scikit-ci scikit-ci-addons"
  - "%PYTHON%\\python.exe -m ci_addons --install ../addons"
  - "%PYTHON%\\python.exe ../addons/appveyor/patch_vs2008.py"

build_script:
  - "%PYTHON%\\python.exe setup.py build_ext -f -i"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*.whl
    name: Wheels
