image: Visual Studio 2015
platform: x64

init:
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%

install:
    - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

    # Check that we have the expected version and architecture for Python
    - "python --version"
    - "build.cmd python --version"
    - "build.cmd python -c \"import struct; print(struct.calcsize('P') * 8)\""
    - "build.cmd python -c \"import platform; print(platform.platform())\""
    - "build.cmd python -c \"import platform; print(platform.processor())\""
    - "build.cmd python -c \"import platform; print(platform.architecture())\""

    # install 3rd party libs
    - echo %platform%
    - vcpkg install glib:%platform%-windows
                    libogg:%platform%-windows
                    libtheora:%platform%-windows
                    ffmpeg:%platform%-windows
    - pwd
    - cd c:\tools\vcpkg
    - vcpkg integrate install
    - cd c:\projects\python-videoplayer
    - vcpkg list --triplet x64-windows

build_script:
    - mkdir wheelhouse

    - cmake --version
    - build.cmd python -m pip install --upgrade pip
    - build.cmd python -m pip install scikit-build cython pytest
    #- python.exe -m pip install scikit-build cython conan pytest
    #- python.exe setup.py build_ext --inplace --force -- -D_CONAN=YES -G "Visual Studio 14 2015%arch%"
    - build.cmd python setup.py build_ext --inplace --force -- -D_VCPKG=YES -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake # -G "Visual Studio 14 2015%arch%"
    - build.cmd python setup.py test
    #- python.exe setup.py sdist --dist-dir wheelhouse
    #- python.exe setup.py bdist_wheel --dist-dir wheelhouse


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
