environment:
    matrix:
        # linux
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          APPVEYOR_JOB_NAME: "python37-x64-ubuntu"

        # osx
        - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
          APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"

        # windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x64-vs2015"
          arch: amd64
          platform: x86
          compiler: msvc

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x64-vs2015"
          arch: x86
          platform: x64
          compiler: msvc


stack: python 3.7

init:
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install:
    - python -m pip install cython pkgconfig
    - vcpkg install glib:%platform%-windows

build_script:
    - mkdir wheelhouse

    - 'if "%compiler%"=="msvc" python setup.py build_ext --inplace --force && python setup.py sdist bdist_wheel --dist-dir wheelhouse'

# after_build


artifacts:
    - path: "wheelhouse\\*.whl"
    - name: Wheels
