environment:
    matrix:
        ## linux
        #- APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        #  APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
        #  compiler: gcc

        ## osx
        #- APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
        #  APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"
        #  compiler: clang

        # windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x64-vs2015"

init:
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%

stack: python 3.7

install:
    - cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

build_script:
    - mkdir wheelhouse

    - ps: python.exe -m pip install --upgrade pip
    - ps: python.exe -m pip install scikit-build cython conan pytest
    - ps: python.exe setup.py build_ext --inplace --force -- -D_CONAN=YES -G "Visual Studio 15 2017 Win64"
    - ps: python.exe setup.py test
    #- ps: python.exe setup.py sdist --dist-dir wheelhouse
    #- ps: python.exe setup.py bdist_wheel --dist-dir wheelhouse


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
