image: Visual Studio 2015
platform: x64

cache: c:\tools\vcpkg\installed\

init:
    - set arch= Win64
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%

install:
    - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

    # dumpbin + https://www.appveyor.com/docs/lang/cpp/
    - set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
    #- call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
    #- call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
    - where dumpbin

    # install 3rd party libs
    # use vcpkg
    - vcpkg install glib:%platform%-windows
                    libogg:%platform%-windows
                    libtheora:%platform%-windows
                    ffmpeg:%platform%-windows
    - cd c:\tools\vcpkg
    - vcpkg integrate install
    - vcpkg list --triplet x64-windows
    - cd %APPVEYOR_BUILD_FOLDER%  # c:\projects\python-videoplayer

build_script:
    #- set VERBOSE=1
    - mkdir wheelhouse

    - python -m pip install --upgrade pip
    - python -m pip install scikit-build cython pytest
    - python setup.py bdist_wheel --dist-dir wheelhouse -- -D_VCPKG=YES -DVCPKG_TARGET_TRIPLET:STRING=x64-windows -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
