#cache: c:\tools\vcpkg\installed\
environment:
  SDL_AUDIODRIVER: dummy  # handle alsa issues

  matrix:
    - PYTHON: "C:/Python27-x64"
      PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      TRIPLET: x64-windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      WIN_BUILD: 1
      MINGW_ARCH: "x86_64"
      MINGW_DIR: "mingw64"
      WHL: "videoplayer-1.1.dev0-cp27-cp27m-win_amd64.whl"
      #VCPKG_BUILD: 1
      #VCPKG_TOOLCHAIN: C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TOOLCHAIN: C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TAG: 2020.11-1

    - PYTHON: "C:/Python27"
      PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      TRIPLET: x86-windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      WIN_BUILD: 1
      MINGW_ARCH: "i686"
      MINGW_DIR: "mingw32"
      WHL: "videoplayer-1.1.dev0-cp27-cp27m-win32.whl"
      #VCPKG_BUILD: 1
      #VCPKG_TOOLCHAIN: C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TOOLCHAIN: C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TAG: 2020.07

init:
  - cmd: set PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH%;
  - cmd: echo %PATH%
#  - cmd: set VCPKG_DEFAULT_TRIPLET=%TRIPLET%
#  - cmd: cd c:\tools\vcpkg                  # vcpkg 2020.02.04-nohash / VS 2019
#  - cmd: vcpkg update
#  - cmd: cd c:\projects
#  - cmd: git clone -b %VCPKG_TAG% --single-branch https://github.com/Microsoft/vcpkg.git
#  - cmd: cd vcpkg
#  - cmd: .\bootstrap-vcpkg.bat
#  - cmd: vcpkg install glib:%TRIPLET%       # 2.52.3-14-3
#  - cmd: vcpkg install libogg:%TRIPLET%     # 1.3.4
#  - cmd: vcpkg install libtheora:%TRIPLET%  # 1.2.0alpha1-20170719~vcpkg1-3
#  - cmd: vcpkg install ffmpeg:%TRIPLET%     # 4.3.1
#  - cmd: vcpkg install msinttypes:%TRIPLET% # 2018-02-25
#  - cmd: vcpkg integrate install
#  - cmd: cd %APPVEYOR_BUILD_FOLDER%
#  - ps: Invoke-WebRequest -Uri https://www.dropbox.com/s/p8xv4pktq670q9i/fofix-win32-deppack-20130304-updated.zip?dl=1 -O temp.zip; Get-Item temp.zip | Expand-Archive -DestinationPath "FolderName"; Remove-Item temp.zip

install:
  - ps: wget http://linkid.free.fr/fofix/fofix-win32-deppack-20130304-updated.zip -OutFile deppack.zip
  - ps: 7z x deppack.zip
  #- ps: bash -c "mv fofix-win32-deppack-20130304-updated/deps win_dep"
  - cmd: set PATH=%APPVEYOR_BUILD_FOLDER%\win_dep;%PATH%;
  - cmd: echo %PATH%
  - ps: |
      bash -c "mkdir -p win_dep"
      cd $env:APPVEYOR_BUILD_FOLDER\win_dep
      wget "http://repo.msys2.org/mingw/${env:MINGW_ARCH}/mingw-w64-${env:MINGW_ARCH}-glib2-2.64.2-1-any.pkg.tar.xz" -OutFile glib2.tar.xz
      wget "http://repo.msys2.org/mingw/${env:MINGW_ARCH}/mingw-w64-${env:MINGW_ARCH}-libogg-1.3.4-3-any.pkg.tar.xz" -OutFile libogg.tar.xz
      wget "http://repo.msys2.org/mingw/${env:MINGW_ARCH}/mingw-w64-${env:MINGW_ARCH}-libtheora-1.1.1-4-any.pkg.tar.xz" -OutFile libtheora.tar.xz
      wget "http://repo.msys2.org/mingw/${env:MINGW_ARCH}/mingw-w64-${env:MINGW_ARCH}-ffmpeg-4.2.2-4-any.pkg.tar.xz" -OutFile ffmpeg.tar.xz

      7z x glib2.tar.xz
      7z x libogg.tar.xz
      7z x libtheora.tar.xz
      7z x ffmpeg.tar.xz

      tar xf glib2.tar
      tar xf libogg.tar
      tar xf libtheora.tar
      tar xf ffmpeg.tar

      Get-ChildItem ${env:MINGW_DIR}\lib\lib*.dll.a | %{
        $new_name = $_.Name.SubString(3) -replace ".dll.a", ".lib"
        $new_fullname = Join-Path $_.DirectoryName $new_name
        Rename-Item $_.FullName $new_fullname
      }

      xcopy /s /y ${env:MINGW_DIR}\* .

      bash -c "mkdir include/msinttypes"
      wget https://raw.githubusercontent.com/chemeris/msinttypes/master/stdint.h -OutFile include\msinttypes\stdint.h
      wget https://raw.githubusercontent.com/chemeris/msinttypes/master/inttypes.h -OutFile include\msinttypes\inttypes.h
      cd $env:APPVEYOR_BUILD_FOLDER

  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -U scikit-ci scikit-ci-addons"
  - "%PYTHON%\\python.exe -m ci_addons --install ../addons"
  - "%PYTHON%\\python.exe ../addons/appveyor/patch_vs2008.py"
  - "%PYTHON%\\python.exe -m pip install cython scikit-build cmake ninja"

build_script:
  - "%PYTHON%\\python.exe setup.py build_ext -f -i"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - ps: |
      bash -c "mkdir -p tmp"
      bash -c "mv tests tmp/"
      cd tmp
      wget http://download.blender.org/peach/trailer/trailer_400p.ogg -OutFile tests/trailer_bick-buck-bunny_400p.ogg
      wget http://download.blender.org/peach/trailer/trailer_iphone.m4v -OutFile tests/trailer_bick-buck-bunny_iphone.m4v
  - "%PYTHON%\\python.exe -m pip install ../dist/%WHL%"
  - "%PYTHON%\\python.exe -c \"from videoplayer import _VideoPlayer; print(_VideoPlayer.__version__)\""
  #- "%PYTHON%\\python.exe -m pip install pytest"
  #- "%PYTHON%\\python.exe -m pytest tests"

artifacts:
  - path: dist\*.whl
    name: Wheels
