environment:
  CIBW_ENVIRONMENT_WINDOWS: "VCPKG_BUILD=1 VCPKG_TOOLCHAIN='C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake'"
  CIBW_BEFORE_BUILD: "pip install cython scikit-build cmake ninja"
  CIBW_BUILD: cp27-win32



cache: c:\tools\vcpkg\installed\
stack: python 3.7

init:
  - cmd: vcpkg install glib:x86-windows
                       libogg:x86-windows
                       libtheora:x86-windows
                       ffmpeg:x86-windows
  - cmd: cd c:\tools\vcpkg
  - cmd: vcpkg integrate install
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

install: python -m pip install cibuildwheel==1.3.0

build_script: python -m cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
