cache: c:\tools\vcpkg\installed\
environment:
  matrix:
    - PYTHON: "C:/Python27-x64"
      PYTHON_DIR: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "64"
      TRIPLET: x64-windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      WIN_BUILD: 1
      #VCPKG_BUILD: 1
      #VCPKG_TOOLCHAIN: C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TOOLCHAIN: C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TAG: 2020.11-1

    - PYTHON: "C:/Python27"
      PYTHON_DIR: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      TRIPLET: x86-windows
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      WIN_BUILD: 1
      #VCPKG_BUILD: 1
      #VCPKG_TOOLCHAIN: C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TOOLCHAIN: C:/projects/vcpkg/scripts/buildsystems/vcpkg.cmake
      #VCPKG_TAG: 2020.07

init:
  - cmd: set PATH=%PYTHON_DIR%;%PYTHON_DIR%\Scripts;%PATH%;
  - cmd: echo %PATH%
#  - cmd: set VCPKG_DEFAULT_TRIPLET=%TRIPLET%
#  - cmd: cd c:\tools\vcpkg                  # vcpkg 2020.02.04-nohash / VS 2019
#  - cmd: vcpkg update
#  - cmd: cd c:\projects
#  - cmd: git clone -b %VCPKG_TAG% --single-branch https://github.com/Microsoft/vcpkg.git
#  - cmd: cd vcpkg
#  - cmd: .\bootstrap-vcpkg.bat
#  - cmd: vcpkg install glib:%TRIPLET%       # 2.52.3-14-3
#  - cmd: vcpkg install libogg:%TRIPLET%     # 1.3.4
#  - cmd: vcpkg install libtheora:%TRIPLET%  # 1.2.0alpha1-20170719~vcpkg1-3
#  - cmd: vcpkg install ffmpeg:%TRIPLET%     # 4.3.1
#  - cmd: vcpkg install msinttypes:%TRIPLET% # 2018-02-25
#  - cmd: vcpkg integrate install
#  - cmd: cd %APPVEYOR_BUILD_FOLDER%
#  - ps: Invoke-WebRequest -Uri https://www.dropbox.com/s/p8xv4pktq670q9i/fofix-win32-deppack-20130304-updated.zip?dl=1 -O temp.zip; Get-Item temp.zip | Expand-Archive -DestinationPath "FolderName"; Remove-Item temp.zip

install:
  - ps: wget http://linkid.free.fr/fofix/fofix-win32-deppack-20130304-updated.zip -OutFile deppack.zip
  - ps: 7z x deppack.zip
  - ps: bash -c "mv fofix-win32-deppack-20130304-updated/deps win_dep"
  - cmd: set PATH=%APPVEYOR_BUILD_FOLDER%\win_dep;%PATH%;
  - cmd: echo %PATH%
  - ps: |
      bash -c "mkdir -p win_dep"
      cd $env:APPVEYOR_BUILD_FOLDER\win_dep
      wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-glib2-2.62.1-1-any.pkg.tar.xz -OutFile glib2.tar.xz

      7z x glib2.tar.xz
      xcopy /s /y mingw32\* .
      cd $env:APPVEYOR_BUILD_FOLDER
#      wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-libogg-1.3.4-3-any.pkg.tar.xz -OutFile libogg.tar.xz
#      wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-libtheora-1.1.1-4-any.pkg.tar.xz -OutFile libtheora.tar.xz
#      wget http://repo.msys2.org/mingw/i686/mingw-w64-i686-ffmpeg-4.2.1-2-any.pkg.tar.xz -OutFile ffmpeg.tar.xz

#      7z x libogg.tar.xz
#      7z x libtheora.tar.xz
#      7z x ffmpeg.tar.xz
#
#      Get-ChildItem mingw32\lib\lib*.dll.a | %{
#        $new_name = $_.Name.SubString(3) -replace ".dll.a", ".lib"
#        $new_fullname = Join-Path $_.DirectoryName $new_name
#        Rename-Item $_.FullName $new_fullname
#      }
#      # Copy all libs and includes under the dependencies folder
#      xcopy /s /y mingw32\* .
#      bash -c "mv mingw32/* ."

  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -U scikit-ci scikit-ci-addons"
  - "%PYTHON%\\python.exe -m ci_addons --install ../addons"
  - "%PYTHON%\\python.exe ../addons/appveyor/patch_vs2008.py"
  - "%PYTHON%\\python.exe -m pip install cython scikit-build cmake ninja"

build_script:
  - "%PYTHON%\\python.exe setup.py build_ext -f -i"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*.whl
    name: Wheels
