image: Visual Studio 2015
platform: x64

cache: c:\tools\vcpkg\installed\

install:
    - set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%
    - ps: ./.appveyor/before_build.ps1

build_script:
    #- set VERBOSE=1
    - mkdir wheelhouse

    - python -m pip install --upgrade pip
    - python -m pip install scikit-build cython pytest
    - python setup.py bdist_wheel --dist-dir wheelhouse -- -D_VCPKG=YES -DVCPKG_TARGET_TRIPLET:STRING=x64-windows -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    # -G "Visual Studio 14 2015 Win64"


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
