environment:

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
      CIBW_BEFORE_BUILD: "bash .github/workflows/before_build.sh linux"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      APPVEYOR_JOB_NAME: "python37-x64-vs2015"
      CIBW_BEFORE_BUILD: "bash .github/workflows/before_build.sh windows"
      VCPKG_BUILD: 1
      VCPKG_TOOLCHAIN: "C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
      APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"
      CIBW_BEFORE_BUILD: "bash .github/workflows/before_build.sh macos"

stack: python 3.7

init:
- cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%

install: python -m pip install cibuildwheel==1.7.0

build_script: python -m cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
