environment:
    matrix:
        ## linux
        #- APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        #  APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
        #  compiler: gcc

        ## osx
        #- APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
        #  APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"
        #  compiler: clang

        # windows
        - MSYS2_ARCH: i686
          MSYSTEM: MINGW32
          MSYSTEM_: mingw32
          platform: x86
          compiler: msvc
          PKG_PREFIX: "mingw-w64-i686"
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x86-vs2015"

        - MSYS2_ARCH: x86_64
          MSYSTEM: MINGW64
          MSYSTEM_: mingw64
          platform: x64
          compiler: msvc
          PKG_PREFIX: "mingw-w64-x86_64"
          APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          APPVEYOR_JOB_NAME: "python37-x64-vs2015"
        #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        #  APPVEYOR_JOB_NAME: "python37-x86-vs2015"
        #  arch: x86
        #  platform: x86
        #  compiler: msvc
        #  arch_mingw: mingw-w64-i686-

        #- APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        #  APPVEYOR_JOB_NAME: "python37-x64-vs2015"
        #  arch: amd64
        #  platform: x64
        #  compiler: msvc
        #  arch_mingw: mingw-w64-x86_64-

matrix:
    fast_finish: true

stack: python 3.7

init:
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    #- set "PYTHON_ROOT=C:\python37-x64"
    #- set "PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%"
    - set "PATH=C:\Python37;C:\Python37\Scripts;%PATH%"

install:
    - if "%compiler%"=="msvc"
        vcpkg install glib:%platform%-windows
                      libogg:%platform%-windows
                      libtheora:%platform%-windows
                      ffmpeg:%platform%-windows
    - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
    - C:\msys64\usr\bin\pacman --noconfirm --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel
    - C:\msys64\usr\bin\pacman -S --noconfirm --needed --noprogressbar
        autoconf automake base-devel %PKG_PREFIX%-toolchain %PKG_PREFIX%-pkg-config
    #    %PKG_PREFIX%-libogg
    #    %PKG_PREFIX%-libtheora
    #    %PKG_PREFIX%-ffmpeg
    #    %PKG_PREFIX%-freeglut
    #    %PKG_PREFIX%-glew
        %PKG_PREFIX%-glib2
    - set "PATH=C:\\msys64\\%MSYSTEM%\\bin;C:\\msys64\\usr\\bin;C:\\msys64\\bin;%PATH%"
    - doskey pkg-config=%MSYS2_ARCH%-w64-mingw32-pkg-config
    - C:\Python37\python -m pip install cython pkgconfig

build_script:
    - mkdir wheelhouse

    - C:\Python37\python setup.py build_ext --inplace --force #--compiler=mingw32
    - C:\Python37\python setup.py sdist --dist-dir wheelhouse
    - C:\Python37\python setup.py bdist_wheel --dist-dir wheelhouse

# after_build


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
