environment:
    matrix:
        ## linux
        #- APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
        #  APPVEYOR_JOB_NAME: "python37-x64-ubuntu"
        #  compiler: gcc

        ## osx
        #- APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
        #  APPVEYOR_JOB_NAME: "python37-x64-macos-mojave"
        #  compiler: clang

        # windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          APPVEYOR_JOB_NAME: "python37-x64-vs2017"
          arch: Win64
          platform: x64

stack: python 3.7

init:
    - set arch=
    - if "%arch%"=="Win64" ( set arch= Win64)
    - echo %arch%
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%

install:
    - cmd: set PATH=C:\Python37;C:\Python37\Scripts;%PATH%
    # C:\msys64\usr\bin\pacman -S --noconfirm mingw64/mingw-w64-x86_64-python3
    - cmd: vcpkg install glib:%platform%-windows
                         libogg:%platform%-windows
                         libtheora:%platform%-windows
                         ffmpeg:%platform%-windows
    - pwd
    - cd c:\tools\vcpkg
    - vcpkg integrate install
    - cd c:\projects\python-videoplayer
    - vcpkg list --triplet x64-windows

build_script:
    - mkdir wheelhouse

    - cmd: cmake --version
    - cmd: python.exe -c 'import setuptools; print(setuptools.__version__)'
    - cmd: python.exe -m pip install --upgrade pip
    - cmd: python.exe -m pip install scikit-build cython pytest
    #- cmd: python.exe -m pip install scikit-build cython conan pytest
    #- cmd: python.exe setup.py build_ext --inplace --force -- -D_CONAN=YES -G "Visual Studio 14 2015%arch%"
    - cmd: python.exe setup.py build_ext --inplace --force -- -D_VCPKG=YES -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
    - cmd: python.exe setup.py test
    #- cmd: python.exe setup.py sdist --dist-dir wheelhouse
    #- cmd: python.exe setup.py bdist_wheel --dist-dir wheelhouse


artifacts:
    - path: "wheelhouse\\*.whl"
      name: Wheels
