language: python
python:
    - 2.7
#    - 3.4
#    - 3.5
#    - 3.6
#    - 3.7
    - 3.8

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y
        libglew-dev
        freeglut3-dev
        libogg-dev
        libswscale-dev
        libtheora-dev

install:
    - pip install scikit-build cmake ninja
    - pip install cython
    - pip install pytest

script:
    #- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    #- mkdir -p build
    #- cd build
    #- conan install ..
    #- find ~/.conan/data/ffmpeg/4.2.1/bincrafters/stable/ -name "swscale.h"
    - export VERBOSE=1
    - python setup.py check
    - python setup.py build_ext --inplace --force
    - ls _skbuild/*/cmake-build/videoplayer
    - ls _skbuild/*/cmake-install/*
    #- python setup.py test
