language: python
python:
    - 2.7
#    - 3.4
#    - 3.5
#    - 3.6
#    - 3.7
    - 3.8

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y
         freeglut3-dev
#        libogg-dev
#        libswscale-dev
#        libtheora-dev
#
#install:
#    - python -m pip install cython pkgconfig
#    - python -m pip install pytest

install:
    - pip install scikit-build
    - pip install cython
    - pip install conan
    - pip install pytest

script:
    #- conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
    #- mkdir -p build
    #- cd build
    #- conan install ..
    #- find ~/.conan/data/ffmpeg/4.2.1/bincrafters/stable/ -name "swscale.h"
    - python setup.py check
    - python setup.py build_ext --inplace --force -- -D_CONAN=YES
    - python setup.py test
