name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels with cibuildwheel on ${{ matrix.os }} / ${{ matrix.cibw-arch }}
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        #os: [ubuntu-18.04, windows-latest, macos-latest]
        include:
          - runs-on: ubuntu-latest
            cibw-arch: cp27-manylinux_x86_64
            cibw-manylinux: manylinux1
          - runs-on: ubuntu-latest
            cibw-arch: cp36-manylinux_x86_64
            cibw-manylinux: manylinux1

          - runs-on: ubuntu-latest
            cibw-arch: cp27-manylinux_i686
            cibw-manylinux: manylinux1
          - runs-on: ubuntu-latest
            cibw-arch: cp36-manylinux_i686
            cibw-manylinux: manylinux1

          - runs-on: ubuntu-latest
            cibw-arch: cp27-manylinux_x86_64
            cibw-manylinux: manylinux2010
          - runs-on: ubuntu-latest
            cibw-arch: cp36-manylinux_x86_64
            cibw-manylinux: manylinux2010

          - runs-on: ubuntu-latest
            cibw-arch: cp27-manylinux_i686
            cibw-manylinux: manylinux2010
          - runs-on: ubuntu-latest
            cibw-arch: cp36-manylinux_i686
            cibw-manylinux: manylinux2010

          - runs-on: ubuntu-latest
            cibw-arch: cp36-manylinux_x86_64
            cibw-manylinux: manylinux2014

          - runs-on: ubuntu-latest
            cibw-arch: cp36-manylinux_i686
            cibw-manylinux: manylinux2014

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.6.4

      #- name: Install Visual C++ for Python 2.7
      #  if: matrix.python-version == '2.7'
      #  run: choco install vcpython27 -f -y

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: "bash {package}/.github/workflows/before_build.sh ${{ matrix.runs-on }}"
          CIBW_BUILD_VERBOSITY: 0
          CIBW_BUILD: "${{ matrix.cibw-arch }}"
          CIBW_MANYLINUX_X86_64_IMAGE: "${{ matrix.cibw-manylinux }}"
          CIBW_MANYLINUX_I686_IMAGE: "${{ matrix.cibw-manylinux }}"

      #- name: Upload wheels
      #  uses: actions/upload-artifact@v2
      #  with:
      #    path: ./wheelhouse/*.whl
