name: Build Linux wheels

on: [push, pull_request]

jobs:
  build-linux:

    name: Build wheels on Linux (${{ matrix.cibw-arch }} ${{ matrix.cibw-manylinux }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs-on: ubuntu-latest
            cibw-arch: "cp27-manylinux_x86_64"
            cibw-manylinux: "manylinux2010"
          #- runs-on: ubuntu-latest
          #  cibw-arch: "*manylinux*"
          #  cibw-manylinux: "manylinux2010"

          #- runs-on: ubuntu-latest
          #  cibw-arch: "cp3*-manylinux*"
          #  cibw-manylinux: "manylinux2014"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.6.4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: "bash {package}/.github/workflows/before_build.sh ${{ matrix.runs-on }}"
          CIBW_BUILD: "${{ matrix.cibw-arch }}"
          CIBW_MANYLINUX_X86_64_IMAGE: "${{ matrix.cibw-manylinux }}"
          CIBW_MANYLINUX_I686_IMAGE: "${{ matrix.cibw-manylinux }}"
          CIBW_BEFORE_TEST: "cp -r {project}/tests /tmp/"
          CIBW_TEST_COMMAND: "pytest /tmp/tests"
          CIBW_TEST_REQUIRES: "pytest"

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          name: wheels_${{ runner.os }}


  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
          name: sdist.tar.gz
