name: Build MacOS wheels

on: [push, pull_request]

jobs:
  build-macos:

    name: Build wheels on MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [2.7, '3.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python {{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install os dependencies
        run: |
          brew update
          brew install \
            glib \
            ffmpeg

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          #python -m pip install cibuildwheel==1.6.4

      - name: Build the wheel
        run: |
          #python -m cibuildwheel --output-dir wheelhouse
          python setup.py build_ext --inplace --force
          python setup.py sdist
          python setup.py bdist_wheel

