name: Build MacOS wheels

on: [push, pull_request]

jobs:
  build-macos:

    name: Build wheels on MacOS
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==1.6.4

      - name: Install os dependencies
        run: |
          brew update
          brew install \
            glib \
            libogg \
            theora \
            ffmpeg

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: "bash {package}/.github/workflows/before_build.sh ${{ runner.os }}"
          CIBW_BUILD: "*macosx*"
          CIBW_TEST_COMMAND: "pytest {package}/tests"
          CIBW_TEST_REQUIRES: "pytest"

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
